#!/bin/bash
for var in rmat-8 rmat-9 rmat-10 rmat-11 rmat-12 random-8 random-9 random-10 random-11 random-12
do
bsub -n 40 -R "span[ptile=20]" -o src/$var.out mpiexec python Graph.py src/$var src/$var.res
done